<?php
return [
    // Anvil Awards Config
    'ANVIL_AWARDS_API_URL' => env('ANVIL_AWARDS_API_URL'),
    'ANVIL_AWARDS_API_CONSUMER_KEY' => env('ANVIL_AWARDS_API_CONSUMER_KEY'),
    'ANVIL_AWARDS_API_CONSUMER_SECRET' => env('ANVIL_AWARDS_API_CONSUMER_SECRET'),

    // Osticket Config
    'OSTICKET_API_URL' => env('OSTICKET_API_URL'),
    'OSTICKET_API_USER' => env('OSTICKET_API_USER'),
    'OSTICKET_API_PASS' => env('OSTICKET_API_PASS'),
];
